spring:
  config:
    import: "optional:classpath:secrets.yml"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOSTNAME}/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  sql:
    init:
      platform: mysql

  jpa:
    hibernate:
      ddl-auto: create # create-drop, update, validate, none
    properties:
      hibernate:
        format_sql: true # SQL 포맷팅
        show_sql: true # SQL 출력
        dialect: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret-key: NiOeyFbN1Gqo10bPgUyTFsRMkJpGLXSvGP04eFqj5B30r5TcrtlSXfQ7TndvYjNvfkEKLqILn0j1SmKODO1Yw3JpBBgI3nVPEahqxeY8qbPSFGyzyEVxnl4AQcrnVneI
  issuer: duduk.shop
  access:
    expiration: 3600000 # 1시간 (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h))
    header: Authorization
  refresh:
    expiration: 1209600000 # 2주 (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> 하루) * 14(2주))
    header: Authorization-refresh

cloud:
  aws:
    s3:
      bucket: ${cloud.aws.s3.bucket}
    stack:
      auto: ${cloud.aws.stack.auto}
    region:
      static: ${cloud.aws.region.static}
    credentials:
      access-key: ${cloud.aws.credentials.access-key}
      secret-key: ${cloud.aws.credentials.secret-key}
