server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id : user-service
            uri: http://localhost:8081/users/**
            predicates:
              - Path=/users/**
          - id : photo-service
            uri: http://localhost:8082/photo/**
            predicates:
              - Path=/photo
          - id : qr-service
            uri: http://localhost:8083/qr/**
            predicates:
              - Path=/qr/**