server:
  port: 0

spring:
  application:
    name: user-service

  eureka:
    instance:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    client:
      register-with-eureka: true
      fetch-registry: true
#      유레카 서버의 위치
      service-url:
        http://localhost:8761/eureka

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: